@startuml
left to right direction

actor "サーバ管理者" as admin

rectangle "導入" {
  usecase "インストール" as UC_inst1
  usecase "PostgreSQL クラスタ初期化" as UC_inst2
  usecase "PostgreSQL サーバへの接続設定" as UC_inst3

}
admin --> (UC_inst1) : サービス提供を開始したいため
admin --> (UC_inst2) : PostgreSQL サーバに必要な資材を生成するため
admin --> (UC_inst3) : ?

rectangle "廃止" {
  usecase "アンインストール" as UC2
}
admin --> (UC2) : サービス提供を終了したいため



@enduml
