---
title: "OSS-DB Gold"
weight: 1
---
= OSS-DB Gold

== OSS-DB Gold とは

オープンソースデータベース技術者認定資格（ OSS-DB 技術者認定資格）のうち、「大規模データベースシステムの改善・運用管理・コンサルティングができる技術者」
向けのレベル

OSS-DB 技術者認定資格とは

[quote, LPI-Japan, 'https://oss-db.jp/outline[試験概要]']
____
特定非営利活動法人エルピーアイジャパン（LPI-Japan）が、オープンソースデータベース（OSS-DB）に関する技術力と知識を、公平かつ厳正に、
中立的な立場で認定するIT技術者認定資格です。 企業で必要とされる技術者は、様々なデータベースの知識を持ち、
顧客に最適なデータベースシステムを提案し、構築・運用できる技術者になる為、OSS-DB技術者認定資格は、
企業から必要とされるデータベース技術者を認定する資格となります。
____


OSS-DB Gold では、下記のスキルと知識を持つエンジニアであることを証明する。

https://oss-db.jp/outline/gold

* RDBMSとSQLに関する知識を有する。
* オープンソースデータベースに関する深い知識を有する。
* オープンソースを利用して大規模なデータベースの運用管理ができる。
* オープンソースを利用して大規模なデータベースの開発を行う事ができる。
* PostgreSQLなどのOSS-DBの内部構造を熟知している。
* PostgreSQLなどのOSS-DBの利用方法やデータベースの状態を検証してパフォーマンスチューニングをすることができる。
* PostgreSQLなどのOSS-DBの利用方法やデータベースの状態を検証してトラブルシューティングをすることができる。

`PostgreSQLなど` とあるが、実際には PostgreSQL 以外の DB は登場しない。

ifdef::env-asciidoctor[]
:leveloffset: +1

include::coverage.adoc[]

include::./management/_index.adoc[]

include::./monitoring/_index.adoc[]

include::./performance/_index.adoc[]

include::./trouble/_index.adoc[]

:leveloffset: -1
endif::[]
