= 動作確認用コード群

学習に際して実際に PostgreSQL で動作確認をするためのコード群を記載する。

== #【未定稿】【検証中】# テーブル容量見積もり

[source, sql]
----
CREATE TABLE tbl_sample_filesize (
    col01 smallint, -- 2 バイト
    col02 integer,  -- 4 バイト
    col03 bigint,  -- 8 バイト
    col04 real,  -- 4 バイト
    col05 double precision,  -- 8 バイト
    col06 timestamp,  -- 8 バイト
    col07 date,  -- 4 バイト
    col08 time,  -- 8 バイト
    col09 interval,  -- 16 バイト
    col10 boolean  -- 1 バイト
    -- 合計 63 バイト
);
----

[source,shell]
----
rm -rf data_tbl_sample_filesize.csv
for i in `seq 1 500000`; do
  echo "1,1000,2000,12.345,67.890,'2021-1-1 12:10:20','2021-1-1','12:10:20','3 4:05:06',true" >> data_tbl_sample_filesize.csv
done

psql -U postgres -c "\copy tbl_sample_filesize FROM 'data_tbl_sample_filesize.csv' WITH csv"
----

[source,console]
----
# ls -lh data_tbl_sample_filesize.csv
-rw-r--r-- 1 root root 41M May 16 10:46 data_tbl_sample_filesize.csv

# psql -U postgres -c "SELECT * FROM tbl_sample_filesize LIMIT 1"
 col01 | col02 | col03 | col04  | col05 |        col06        |   col07    |  col08   |      col09      | col10 
-------+-------+-------+--------+-------+---------------------+------------+----------+-----------------+-------
     1 |  1000 |  2000 | 12.345 | 67.89 | 2021-01-01 12:10:20 | 2021-01-01 | 12:10:20 | 3 days 04:05:06 | t
(1 row)

# psql -U postgres -c "SELECT COUNT(*) FROM tbl_sample_filesize"
 count  
--------
 500000
(1 row)

### https://www.postgresql.jp/document/11/html/functions-admin.html#FUNCTIONS-ADMIN-DBSIZE
# psql -U postgres -c "SELECT pg_size_pretty((pg_stat_file(pg_relation_filepath('tbl_sample_filesize'))).size) as filesize"
 filesize 
----------
 52 MB
(1 row)

# psql -U postgres -c "SELECT pg_size_pretty(pg_relation_size('tbl_sample_filesize'))"
 pg_size_pretty 
----------------
 52 MB
(1 row)

# psql -U postgres -c "ANALYZE tbl_sample_filesize"

# psql -U postgres -c "SELECT pg_relation_filepath(oid), relpages, reltuples FROM pg_class WHERE relname = 'tbl_sample_filesize'"
 pg_relation_filepath | relpages | reltuples 
----------------------+----------+-----------
 base/13067/24579     |     6667 |    500000
(1 row)

echo $(( 8192 / (28+59) ))

echo $(( 500000 / ( (8192-24) / (28+63) ) ))
# echo $(( 500000 / ( (8192-24) / (28+63) ) ))
5617

echo $(( (8192-24) / (28+63) ))
echo $(( 8192 * ( 500000 / ( (8192-24) / (28+63) ) ) / 1024 / 1024 ))

echo $(( 500000 / 6667 ))
74

echo $(( (8192-24) / 74 ))
110

echo $(( 500000 / 5617 ))
89

echo $(( (8192-24) / 89 ))
91
----

[source, sql]
----
DROP TABLE tbl_sample_filesize ;
----

[source,console]
----

CREATE TABLE registration (
  id BIGINT PRIMARY KEY,
  reg_event INTEGER NOT NULL,
  reg_client INTEGER NOT NULL,
  reg_date TIMESTAMP NOT NULL
);

# rm -rf data_registration.csv
# for i in `seq 1 500000`; do
  echo "$i,1000,2000,'2021-1-1 12:10:20'" >> data_registration.csv
done

# psql -U postgres -c "\copy registration FROM 'data_registration.csv' WITH csv"

# psql -U postgres -c "SELECT pg_size_pretty(pg_relation_size('registration'))"
 pg_size_pretty 
----------------
 25 MB
(1 row)

# echo $(( 8192 * ( 500000 / ( (8192-24) / (28+24) ) ) / 1024 / 1024 ))
24

# psql -U postgres -c "SELECT pg_relation_filepath(oid), relpages, reltuples FROM pg_class WHERE relname = 'registration'"
 pg_relation_filepath | relpages | reltuples 
----------------------+----------+-----------
 base/13067/24587     |     3185 |    500000
(1 row)

# psql -U postgres -c "SELECT pg_column_size(col01) FROM tbl_sample_filesize LIMIT 1"

# psql -U postgres -c "EXPLAIN SELECT * FROM tbl_sample_filesize LIMIT 1"
                                    QUERY PLAN                                     
-----------------------------------------------------------------------------------
 Limit  (cost=0.00..0.02 rows=1 width=63)
   ->  Seq Scan on tbl_sample_filesize  (cost=0.00..11667.00 rows=500000 width=63)
(2 rows)
----

== pg_stats

[source, sql]
----
CREATE TABLE tbl_sample_stats (
    col01 integer,
    col02 integer,
    col03 integer,
    col04 char(5)
);

CREATE INDEX idx_sample_stats_1 ON tbl_sample_stats (col01 NULLS FIRST);
CREATE INDEX idx_sample_stats_2 ON tbl_sample_stats (col02 NULLS FIRST);

INSERT INTO tbl_sample_stats VALUES(1,5,2,'aaa');
INSERT INTO tbl_sample_stats VALUES(2,4,3,'aaa');
INSERT INTO tbl_sample_stats VALUES(3,3,3,'bbb');
INSERT INTO tbl_sample_stats VALUES(4,2,1,'bbb');
INSERT INTO tbl_sample_stats VALUES(5,1,5,'ccc');
INSERT INTO tbl_sample_stats VALUES(6,NULL,NULL,'ddd');
----

[source, sql]
----
postgres=# SELECT ctid, * FROM tbl_sample_stats;
 ctid  | col01 | col02 | col03 | col04 
-------+-------+-------+-------+-------
 (0,1) |     1 |     5 |     2 | aaa  
 (0,2) |     2 |     4 |     3 | aaa  
 (0,3) |     3 |     3 |     3 | bbb  
 (0,4) |     4 |     2 |     1 | bbb  
 (0,5) |     5 |     1 |     5 | ccc  
 (0,6) |     6 |       |       | ddd  
(6 rows)
----

[source, sql]
----
postgres=# ANALYZE tbl_sample_stats;
ANALYZE
----

[source, sql]
----
postgres=# \x
Expanded display is on.
postgres=# SELECT * FROM pg_stats WHERE tablename = 'tbl_sample_stats';
-[ RECORD 1 ]----------+--------------------
schemaname             | public
tablename              | tbl_sample_stats
attname                | col01
inherited              | f
null_frac              | 0
avg_width              | 4
n_distinct             | -1
most_common_vals       | 
most_common_freqs      | 
histogram_bounds       | {1,2,3,4,5,6}
correlation            | 1
most_common_elems      | 
most_common_elem_freqs | 
elem_count_histogram   | 
-[ RECORD 2 ]----------+--------------------
schemaname             | public
tablename              | tbl_sample_stats
attname                | col02
inherited              | f
null_frac              | 0.166667
avg_width              | 4
n_distinct             | -0.833333
most_common_vals       | 
most_common_freqs      | 
histogram_bounds       | {1,2,3,4,5}
correlation            | -1
most_common_elems      | 
most_common_elem_freqs | 
elem_count_histogram   | 
-[ RECORD 3 ]----------+--------------------
schemaname             | public
tablename              | tbl_sample_stats
attname                | col03
inherited              | f
null_frac              | 0.166667
avg_width              | 4
n_distinct             | -0.666667
most_common_vals       | {3}
most_common_freqs      | {0.333333}
histogram_bounds       | {1,2,5}
correlation            | 0.4
most_common_elems      | 
most_common_elem_freqs | 
elem_count_histogram   | 
-[ RECORD 4 ]----------+--------------------
schemaname             | public
tablename              | tbl_sample_stats
attname                | col04
inherited              | f
null_frac              | 0
avg_width              | 6
n_distinct             | -0.666667
most_common_vals       | {"aaa  ","bbb  "}
most_common_freqs      | {0.333333,0.333333}
histogram_bounds       | {"ccc  ","ddd  "}
correlation            | 1
most_common_elems      | 
most_common_elem_freqs | 
elem_count_histogram   | 
----

[source, sql]
----
postgres=# CLUSTER tbl_sample_stats USING idx_sample_stats_2;
CLUSTER
postgres=# \x
Expanded display is off.
postgres=# SELECT ctid, * FROM tbl_sample_stats;
 ctid  | col01 | col02 | col03 | col04 
-------+-------+-------+-------+-------
 (0,1) |     6 |       |       | ddd  
 (0,2) |     5 |     1 |     5 | ccc  
 (0,3) |     4 |     2 |     1 | bbb  
 (0,4) |     3 |     3 |     3 | bbb  
 (0,5) |     2 |     4 |     3 | aaa  
 (0,6) |     1 |     5 |     2 | aaa  
(6 rows)
----

[source, sql]
----
postgres=# ANALYZE tbl_sample_stats;
ANALYZE
postgres=# \x
Expanded display is on.
postgres=# SELECT * FROM pg_stats WHERE tablename = 'tbl_sample_stats';
-[ RECORD 1 ]----------+--------------------
schemaname             | public
tablename              | tbl_sample_stats
attname                | col01
inherited              | f
null_frac              | 0
avg_width              | 4
n_distinct             | -1
most_common_vals       | 
most_common_freqs      | 
histogram_bounds       | {1,2,3,4,5,6}
correlation            | -1
most_common_elems      | 
most_common_elem_freqs | 
elem_count_histogram   | 
-[ RECORD 2 ]----------+--------------------
schemaname             | public
tablename              | tbl_sample_stats
attname                | col02
inherited              | f
null_frac              | 0.166667
avg_width              | 4
n_distinct             | -0.833333
most_common_vals       | 
most_common_freqs      | 
histogram_bounds       | {1,2,3,4,5}
correlation            | 1
most_common_elems      | 
most_common_elem_freqs | 
elem_count_histogram   | 
-[ RECORD 3 ]----------+--------------------
schemaname             | public
tablename              | tbl_sample_stats
attname                | col03
inherited              | f
null_frac              | 0.166667
avg_width              | 4
n_distinct             | -0.666667
most_common_vals       | {3}
most_common_freqs      | {0.333333}
histogram_bounds       | {1,2,5}
correlation            | -0.3
most_common_elems      | 
most_common_elem_freqs | 
elem_count_histogram   | 
-[ RECORD 4 ]----------+--------------------
schemaname             | public
tablename              | tbl_sample_stats
attname                | col04
inherited              | f
null_frac              | 0
avg_width              | 6
n_distinct             | -0.666667
most_common_vals       | {"aaa  ","bbb  "}
most_common_freqs      | {0.333333,0.333333}
histogram_bounds       | {"ccc  ","ddd  "}
correlation            | -0.885714
most_common_elems      | 
most_common_elem_freqs | 
elem_count_histogram   | 
----
