@startuml
/'
コメント
'/
legend
凡例
endlegend

abstract "abstract"
abstract class "abstract class"
annotation "annotation"
circle "circle"
() "circle_short_form"
class "class"
diamond diamond
<> diamond_short_form
entity "entity"
enum "enum"
interface "interface"


"Class07" .. "Class08" : "依存"
"Class07-2" <.. "Class08-2" : "依存"
"Class01a" <|-- "Class02a" : "汎化\n 継承"
"Class01b" <|.. "Class02b" : "実現\n 実装"

/'
関連クラス
'/
class Student {
  Name
}
Student "0..*" - "1..*" Course
  (Student, Course) .. Enrollment
  class Enrollment {
  drop()
  cancel()
}

/'
複数関連
'/
class Station {
  +name: string
}
class StationCrossing {
  +cost: TimeInterval
}
<> diamond1
StationCrossing . diamond1
diamond1 - "from 0..*" Station
diamond1 - "to 0..* " Station



@enduml
