@startuml
/'
"全体" "0..1" o--> "*" "部分" : "（共有）集約\n aggregation"
'/
legend
凡例
（共有）集約 aggregation
endlegend

/'
Sometimes a Property is used to model circumstances in which one instance is used to group together a set of instances; 
this is called aggregation.
'/

"全体" "0..1" o--> "*" "部分" : "（共有）集約\n aggregation"
note right on link
part-of
関連の一種
1つのインスタンス（全体）で複数のインスタンス（部分）を
グループ化するモデルをプロパティを使って表現？
部分側は他と共有可能（ shared aggregation ）

三角形とその辺？
図書館と本？
end note


@enduml
