@startuml
/'
"Class01" "*" -- "*" "Class02" : "関連\n association"
'/
legend
凡例
関連 association
endlegend

"Class01" "*" -- "*" "Class02" : "関連\n association"
note right on link
has-a
どちらかが参照を保持
end note

"Class01-2" "1" <--x "1" "Class02-2" : "関連"
note right on link
誘導可能性を示した版
（どちらからどちらを操作できるか）
end note

/'
plantuml では多重度とロールを分ける記法がないため、うまいこと書くしかない
* は書く場所によってはエスケープが必要
'/
"Class01-3" "*\n所有物" <--x "1\n所有者" "Class02-3" : < "所有"
note right on link
関連の方向を示した版
end note


@enduml
