@startuml
/'
"Class01" <|-- "Class02"
"Class03" *-- "Class04"
"Class05" o-- "Class06"
"Class07" .. "Class08"
"Class09" -- "Class10"
'/
legend
凡例
endlegend

"Class01" "*" -- "*" "Class02" : "関連\n association"
note right on link
has-a
どちらかが参照を保持
end note

"Class01-2" "1" <-- "1" "Class02-2" : "関連"
note right on link
関係の方向を示した版
end note


"Class07" .. "Class08" : "依存"
"Class07-2" <.. "Class08-2" : "依存"
"Class01a" <|-- "Class02a" : "汎化\n 継承"
"Class01b" <|.. "Class02b" : "実現\n 実装"

/'
関連クラス
'/
class Student {
  Name
}
Student "0..*" - "1..*" Course
  (Student, Course) .. Enrollment
  class Enrollment {
  drop()
  cancel()
}

/'
複数関連
'/
class Station {
  +name: string
}
class StationCrossing {
  +cost: TimeInterval
}
<> diamond
StationCrossing . diamond
diamond - "from 0..*" Station
diamond - "to 0..* " Station



@enduml
