@startuml

/'
"Class01" <|-- "Class02"
"Class03" *-- "Class04"
"Class05" o-- "Class06"
"Class07" .. "Class08"
"Class09" -- "Class10"
'/

"DBMS" <|-- RDBMS
"RDBMS" <|-- ORDBMS
"ORDBMS" <|-- PostgreSQL
"PostgreSQL" *-- "PostgreSQL サーバー"
"PostgreSQL" *-- "PostgreSQL クライアント"
"PostgreSQL" *-- "PostgreSQL ユーザー"
"PostgreSQL サーバー" <.. "PostgreSQL クライアント"

"Class01" <|-- "Class02"
"Class03" *-- "Class04"
"Class05" o-- "Class06"
"Class07" .. "Class08"
"Class09" -- "Class10"
@enduml
