---
title: "ユースケース図"
---
= ユースケース図

大まかなユースケースを網羅することで登場するオブジェクトを洗い出す

ユースケースではユーザの操作のみ起点とし、サービス側の動きはシーケンス図の方で記載する？
ただし、他のユーザ操作に関わる動き（接続用ポートの待ち受けを開始するなど）はユースケース内にも記載する。


5W2H で説明する？

.ユースケース一覧
[options="header,autowidth",stripes=hover]
|===
|いつ |どこで |誰が |何故 |何を |どれだけ |どうした
|===

サービス提供者が、データを管理するサービスを提供したいと考える。

DBMS の利用を決定する
PostgreSQL の利用を決定する

サーバ管理者
サービス利用者


設計
見積

CPU
メモリー
ディスク
ネットワーク
利用者数

サービス提供者が予算を決定する。

サービス提供者が利用可能なユーザ数を決定する。
サービス提供者が利用するサーバ台数を決定する。
サービス提供者が利用するサーバのスペックを決定する。
サービス提供者が利用可能なネットワーク帯域を決定する。



導入

サーバ管理者が PostgreSQL サーバをインストールする


設定
起動
停止
状態確認

サーバ管理者が PostgreSQL サーバへの接続に関する情報を設定ファイルに記述する。

サーバ管理者が PostgreSQL サーバを起動する
サーバ管理者が PostgreSQL サーバを停止する
サーバ管理者が PostgreSQL サーバの起動状態を確認する

PostgreSQL サーバが必要なプロセスを起動する


運用
データ準備
データ提供
データ利用

アプリ開発？

サービス利用者がデータを作成する
サービス利用者がデータを格納する
サービス利用者がデータを参照する
サービス利用者がデータを更新する
サービス利用者がデータを削除する



監視
状態
ログ
統計

サーバ管理者が PostgreSQL サーバのログを確認する
サーバ管理者が PostgreSQL サーバの統計情報を確認する
サーバ管理者が PostgreSQL サーバのリソース使用量を確認する

保守
障害対応
移行
バックアップ、リストア
スケールアップ、ダウン
スケールアウト、イン

通信異常でネットワークが遮断される
ディスク異常で書き込みに失敗する
操作ミスでエラーが発生する
電源異常でマシンが停止する



廃止

サーバ管理者が PostgreSQL サーバをアンインストールする


