---
title: "クラス図"
---
= クラス図

クラス図を使ったオブジェクト整理


* オブジェクトの階層関係を表す概要クラス図で包含関係を整理
* 各オブジェクトの詳細クラス図では各クラスの中にあるオブジェクトに対する操作をメソッド、その設定パラメタをメンバとして書いてみる？
** クラス内の各オブジェクトに閉じた操作はそのオブジェクトのクラス内に、複数のオブジェクトに関する操作はそれらを含むクラスのメソッドに書く

オブジェクトの作成／削除を意識すると整理しやすいかもしれない。

* PostgreSQL サーバー／クライアントのインストール／アンインストール
* DB クラスターの作成／削除
* PostgreSQL サービスの起動／停止

など

* インストール／アンインストール
** PostgreSQL サーバー
** PostgreSQL クライアント
** プラグイン？
* 起動／停止
** PostgreSQL サービス
*** 主プロセス（クライアント接続受付け）
*** バックグラウンドプロセス（自動保守系）
**** 自動バキュームランチャー
**** 統計情報コレクター
**** WAL ライター
**** チェックポインター
**** バックグラウンドライター
*** クライアント接続ごとの子プロセス
** サーバーコマンド
*** initdb
*** pg_archivecleanup
*** pg_controldata
*** pg_ctl
*** pg_resetwal
*** pg_rewind
*** pg_test_fsync
*** pg_test_timing
*** pg_upgrade
*** pg_verify_checksums
*** pg_waldump
*** postgres
*** postmaster
** クライアントコマンド
*** clusterdb
*** createdb
*** createuser
*** dropdb
*** dropuser
*** ecpg
*** pg_basebackup
*** pgbench
*** pg_config
*** pg_dump
*** pg_dumpall
*** pg_isready
*** pg_receivewal
*** pg_recvlogical
*** pg_restore
*** psql
*** reindexdb
*** vacuumdb
* 作成／削除
** DB クラスター
** SQL の DDL で定義される各オブジェクト
** WAL？
** 各種ログ？

意識して作成などはしないが内部で自動操作されるかつ利用者も存在を確認できるものに注意

SQL や設定ファイルなど、インターフェースとなるものも一旦はオブジェクトとして一覧にし、 OOUI で整理？

プロセスやファイル、メモリなどの種別を表すために、それらの継承もしておく？

公式ドキュメントに出てくる名詞／形容詞／動詞とその関係性は意識しておくこと


++++
<div class="mermaid">
classDiagram
  DBMS <|-- RDBMS
  RDBMS <|-- ORDBMS
  ORDBMS <|-- PostgreSQL

  PostgreSQL *-- PostgreSQL サーバー
  PostgreSQL *-- PostgreSQL クライアント
  PostgreSQL *-- PostgreSQL ユーザー

  PostgreSQL サーバー <.. PostgreSQL クライアント
</div>

<div class="mermaid">
classDiagram
  PostgreSQL サーバー *-- DB クラスター
  PostgreSQL サーバー *-- ログ
  PostgreSQL サーバー *-- レプリケーションサーバー

  DB クラスター <.. PostgreSQL クライアント
  DB クラスター <.. レプリケーションサーバー

  レプリケーションサーバー <.. PostgreSQL クライアント
</div>


<div class="mermaid">
classDiagram
  PostgreSQL サービス <|-- 主プロセス クライアント接続受付け
  PostgreSQL サービス <|-- バックグラウンドプロセス 自動保守系
  PostgreSQL サービス <|-- クライアント接続ごとの子プロセス

  バックグラウンドプロセス 自動保守系 <|-- 自動バキュームランチャー
  バックグラウンドプロセス 自動保守系 <|-- 統計情報コレクター
  バックグラウンドプロセス 自動保守系 <|-- WAL ライター
  バックグラウンドプロセス 自動保守系 <|-- チェックポインター
  バックグラウンドプロセス 自動保守系 <|-- バックグラウンドライター
</div>


<div class="mermaid">
classDiagram
  SQL の DDL で定義される各オブジェクト <|-- ACCESS METHOD
  SQL の DDL で定義される各オブジェクト <|-- AGGREGATE
  SQL の DDL で定義される各オブジェクト <|-- CAST
  SQL の DDL で定義される各オブジェクト <|-- COLLATION
  SQL の DDL で定義される各オブジェクト <|-- CONVERSION
  SQL の DDL で定義される各オブジェクト <|-- DATABASE
  SQL の DDL で定義される各オブジェクト <|-- DOMAIN
  SQL の DDL で定義される各オブジェクト <|-- EVENT TRIGGER
  SQL の DDL で定義される各オブジェクト <|-- EXTENSION
  SQL の DDL で定義される各オブジェクト <|-- FOREIGN DATA WRAPPER
  SQL の DDL で定義される各オブジェクト <|-- FOREIGN TABLE
  SQL の DDL で定義される各オブジェクト <|-- FUNCTION
  SQL の DDL で定義される各オブジェクト <|-- GROUP
  SQL の DDL で定義される各オブジェクト <|-- INDEX
  SQL の DDL で定義される各オブジェクト <|-- LANGUAGE
  SQL の DDL で定義される各オブジェクト <|-- MATERIALIZED VIEW
  SQL の DDL で定義される各オブジェクト <|-- OPERATOR
  SQL の DDL で定義される各オブジェクト <|-- OPERATOR CLASS
  SQL の DDL で定義される各オブジェクト <|-- OPERATOR FAMILY
  SQL の DDL で定義される各オブジェクト <|-- POLICY
  SQL の DDL で定義される各オブジェクト <|-- PROCEDURE
  SQL の DDL で定義される各オブジェクト <|-- PUBLICATION
  SQL の DDL で定義される各オブジェクト <|-- ROLE
  SQL の DDL で定義される各オブジェクト <|-- RULE
  SQL の DDL で定義される各オブジェクト <|-- SCHEMA
  SQL の DDL で定義される各オブジェクト <|-- SEQUENCE
  SQL の DDL で定義される各オブジェクト <|-- SERVER
  SQL の DDL で定義される各オブジェクト <|-- STATISTICS
  SQL の DDL で定義される各オブジェクト <|-- SUBSCRIPTION
  SQL の DDL で定義される各オブジェクト <|-- TABLE
  SQL の DDL で定義される各オブジェクト <|-- TABLE AS
  SQL の DDL で定義される各オブジェクト <|-- TABLESPACE
  SQL の DDL で定義される各オブジェクト <|-- TEXT SEARCH CONFIGURATION
  SQL の DDL で定義される各オブジェクト <|-- TEXT SEARCH DICTIONARY
  SQL の DDL で定義される各オブジェクト <|-- TEXT SEARCH PARSER
  SQL の DDL で定義される各オブジェクト <|-- TEXT SEARCH TEMPLATE
  SQL の DDL で定義される各オブジェクト <|-- TRANSFORM
  SQL の DDL で定義される各オブジェクト <|-- TRIGGER
  SQL の DDL で定義される各オブジェクト <|-- TYPE
  SQL の DDL で定義される各オブジェクト <|-- USER
  SQL の DDL で定義される各オブジェクト <|-- USER MAPPING
  SQL の DDL で定義される各オブジェクト <|-- VIEW

</div>

++++


