---
title: "データベースマネージメントシステム（ DBMS ）"
weight: 1
---
= データベースマネージメントシステム（ DBMS ）

データベースマネージメントシステム（ DBMS ）とは

データベース（データを蓄積する入れ物と蓄積されたデータ）を管理するシステム

構成物とその役割

[#img-dbms-abst]
.DBMS 概要図
image::dbms-abst.svg[opts=inline,align="center",width=100%]

サーバとクライアントで構成される

* クライアントからはデータの格納や参照の依頼
* サーバからは依頼に対する各種メッセージや参照したデータ

使い方、作業フロー概略

1. aaa
2. bbb

クライアントにはCLIやGUI、ライブラリなど

関連するコンセプト

* データベースサーバ
* データベースクライアント
* データベース


サーバの各機能のI/Fは基本的にはクライアントとなるため、機能の説明をする際には
サーバとクライアントセットで行う。そのため、機能概要ではサーバとクライアントは分けないドキュメント構成とする。
リファレンスの方ではサーバ用とクライアント用は分ける。

概要図は直観的に分かるように、名前が付いた箱などを大きめに少なく配置、番号なしでも分かるように説明

詳細図は多くのものを登場させるため、いろんな図形でグループ分けはできるようにしつつ、名前も省略して吹き出しのようなもので採番だけして、図の外で名前などを一覧化

概要の一覧はリファレンスのパラメタ一覧のグルーピングと一致させた方が分かりやすい

リファレンスの方はより詳細に分割する可能性はある

[#img-server-single-abst]
.データベースサーバ概要図
image::server-single-abst.svg[opts=inline,align="center",width=50%]

1. クライアント : ～
2. サーバ : ～
3. 通信ポート : ～



[#img-server-replication-abst]
.データベースサーバ（レプリケーション）概要図
image::server-replication-abst.svg[opts=inline,align="center",width=50%]
