@startuml
left to right direction

/'
actor "誰が" as who

rectangle "いつ" {
  usecase "何をしたい" as UC1
}
who --> (UC1) : 何故
'/

actor "サーバ管理者" as admin


rectangle "障害発生後" {
  usecase "データ復旧" as UC_restore
}
admin --> (UC_restore) : 何故


@enduml
