@startuml
left to right direction

/'
actor "誰が" as who

rectangle "いつ" {
  usecase "何をしたい" as UC1
}
who --> (UC1) : 何故
'/

actor "サーバ管理者" as admin

rectangle "定期的" {
  usecase "データ退避" as UC_backup
}
admin --> (UC_backup) : 何故


@enduml
