---
title: "usecase"
linkTitle: "ユースケース図"
weight: 1
description: >
  ユースケース図.
---
= ユースケース図

////
大まかなユースケースを網羅することで登場するオブジェクトを洗い出す

ユースケースではユーザの操作のみ起点とし、サービス側の動きはシーケンス図の方で記載する？
ただし、他のユーザ操作に関わる動き（接続用ポートの待ち受けを開始するなど）はユースケース内にも記載する。
=> システム内のサブユースケースとして書くかどうかレベル

* ユースケースはコンセプトに反映
** 各コンセプトでは実行可能な手順（イメージを掴むための簡易なもの）と結果も記載。チュートリアルとは別物
=> 実行可能な手順は Overview / Concepts には基本書かない。
* シーケンスやアクティビティは Core Tasks や リファレンスに反映
** 各 Tasks では実行可能な手順と結果も記載。チュートリアルとは別物

目的ベース（サーバに接続するために設定など）で記述し、細かい話（接続設定の中のポート番号など）は別で説明

ユースケースの内容は Overview / Concepts だけで説明ができる範囲
例えば、 DB の起動や停止やサービス仕組みや利用の流れ（管理者が起動後に利用者が利用可能になる）として説明される

Overview / Concepts : ユーザは何ができるか（どんな目的を達成できるか）
GettingStarted / Tasks / Tutorials / Reference : ユーザは何をすべきか（どんな手順が必要となるのか）


tasks の章立てや各章／節の書き出し文章は usecase ベースとなるはず

いきなりユースケース一覧を完成させるのではなく、シーケンス一覧で具体的な操作を洗い出しながら
ユースケースで整理していくのが良さそう
////



////
svg にしておけば図内の文章をコピペ可能
ただし、生成された html 内では base64 変換された状態のため、図だけ別に開くなどが必要？
////
.ユースケース図（凡例）
[plantuml, target=diagram-usecases-legend, format=svg]
....
include::_puml/legend.puml[]
....


////
5W2H で説明する？
=> ユースケースでそこまで書くのは細かすぎる
いつ、誰が、何のために、何をしたい？、くらいが良さそう
////

.ユースケース一覧（凡例）
[options="header,autowidth",stripes=hover]
|===
|いつ |誰が |何のために |何をしたい

|例文
|例文
|例文
|例文


|===




ifdef::env-asciidoctor[]
:leveloffset: +1

include::install/_index.adoc[]
include::operation/_index.adoc[]
include::maintenance/_index.adoc[]


:leveloffset: -1
endif::[]
